// <auto-generated />
using System;
using Home.DataCrawler.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Home.DataCrawler.Migrations
{
    [DbContext(typeof(ValueContext))]
    [Migration("20180512234559_HmStatesSeeding1")]
    partial class HmStatesSeeding1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-preview2-30571");

            modelBuilder.Entity("Home.Domain.Entities.HomeMaticState", b =>
                {
                    b.Property<Guid>("Pk")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset?>("LastEdit");

                    b.Property<string>("Name");

                    b.Property<bool>("State");

                    b.HasKey("Pk");

                    b.ToTable("HomeMaticStates");

                    b.HasData(
                        new { Pk = new Guid("af39e5b0-28c3-4968-b6bd-cbaf6076a0a3"), LastEdit = new DateTimeOffset(new DateTime(2018, 5, 13, 1, 45, 59, 86, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)), Name = "SteckdoseTv", State = false },
                        new { Pk = new Guid("18cc2f3b-1d49-4cc4-8473-3ec2639ba352"), LastEdit = new DateTimeOffset(new DateTime(2018, 5, 13, 1, 45, 59, 90, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)), Name = "Alarmanlage", State = false },
                        new { Pk = new Guid("56adf1bb-cc83-431c-bc29-b14b22fe441a"), LastEdit = new DateTimeOffset(new DateTime(2018, 5, 13, 1, 45, 59, 90, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)), Name = "Deckenlampe", State = false },
                        new { Pk = new Guid("09ac2db5-b118-4627-beb2-28c4be698232"), LastEdit = new DateTimeOffset(new DateTime(2018, 5, 13, 1, 45, 59, 91, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)), Name = "Fenster Bad hinten", State = false },
                        new { Pk = new Guid("ede699f5-19e8-47e5-a2d4-7128d0ed20f6"), LastEdit = new DateTimeOffset(new DateTime(2018, 5, 13, 1, 45, 59, 91, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)), Name = "Fenster Kinderzimmer rechts", State = false },
                        new { Pk = new Guid("c731424d-cbef-4533-994e-b3fe10028afa"), LastEdit = new DateTimeOffset(new DateTime(2018, 5, 13, 1, 45, 59, 91, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)), Name = "Fenster Kinderzimmer links", State = false },
                        new { Pk = new Guid("0e56ebec-47ff-4382-8861-d3f18f660669"), LastEdit = new DateTimeOffset(new DateTime(2018, 5, 13, 1, 45, 59, 91, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)), Name = "Fenster Wohnzimmer rechts", State = false },
                        new { Pk = new Guid("93b6618a-fd6d-4238-8e22-c43ccf8aef55"), LastEdit = new DateTimeOffset(new DateTime(2018, 5, 13, 1, 45, 59, 91, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)), Name = "Fenster Wohnzimmer links", State = false },
                        new { Pk = new Guid("20b62533-23f2-4bfb-95d4-da3f780367bf"), LastEdit = new DateTimeOffset(new DateTime(2018, 5, 13, 1, 45, 59, 91, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)), Name = "Fenster Terrasse rechts", State = false },
                        new { Pk = new Guid("8de0c218-1a5c-4ac4-b19a-34c2c26445af"), LastEdit = new DateTimeOffset(new DateTime(2018, 5, 13, 1, 45, 59, 91, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)), Name = "Fenster Terrasse links", State = false },
                        new { Pk = new Guid("676229a9-5bf7-49a8-8a8b-62b937c3312e"), LastEdit = new DateTimeOffset(new DateTime(2018, 5, 13, 1, 45, 59, 91, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)), Name = "Fenster Schlafzimmer rechts", State = false },
                        new { Pk = new Guid("77ac877f-6d5b-4e1a-8c78-df07332f09e9"), LastEdit = new DateTimeOffset(new DateTime(2018, 5, 13, 1, 45, 59, 91, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)), Name = "Fenster Schlafzimmer links", State = false }
                    );
                });

            modelBuilder.Entity("Home.Domain.Entities.MeasurePoint", b =>
                {
                    b.Property<string>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChannelId");

                    b.Property<DateTimeOffset?>("Create");

                    b.Property<string>("PointName");

                    b.Property<double>("PointValue");

                    b.HasKey("Guid");

                    b.ToTable("MeasurePoints");
                });

            modelBuilder.Entity("Home.Domain.Entities.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset?>("Created");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
